services:
  bocbot:
    build: .
    image: bocbot:latest
    container_name: bocbot
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/bocbot_ws/src
    stdin_open: true
    tty: true
